### ISSUE TITLE
android.view.InflateException: Binary XML file line #10: Error inflating class com.mattprecious.swirl.SwirlView

### ISSUE THREAD

**Issue by specialshoot** [mattprecious/swirl#2]
不管是下载源码还是直接compile 'com.mattprecious.swirl:swirl:1.0.0'，都报这个错误
No matter I use code directly or add 'com.mattprecious.swirl:swirl:1.0.0' in gradle,this error appears everytime

**Comment by JakeWharton** [comment]
Include the full stack trace. Did you add the required attributes to your theme or the view directly?

**Comment by theblixguy** [comment]
Because it requires API Level 23 to work, that's why you're getting this error

**Comment by MaxChinni** [comment]
Why is API 23 needed?
I recompiled all with these changes and the sample project seems to work anyway.

```
diff --git a/swirl/src/main/java/com/mattprecious/swirl/SwirlView.java b/swirl/src/main/java/com/mattprecious/swirl/SwirlView.java
index e65a8c5..cd77ffb 100644
--- a/swirl/src/main/java/com/mattprecious/swirl/SwirlView.java
+++ b/swirl/src/main/java/com/mattprecious/swirl/SwirlView.java
@@ -27,8 +27,8 @@ public final class SwirlView extends ImageView {
   public SwirlView(Context context, AttributeSet attrs) {
     super(context, attrs);

-    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
-      throw new AssertionError("API 23 required.");
+    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
+      throw new AssertionError("API 22 required.");
     }

     TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.swirl_Swirl);
```

The only problem I noticed is that the morphing effect seems a bit slower and so, if I manage to change the state before the animation completes, the icon remains in an intermediate position.

**Comment by mattprecious** [comment]
The min SDK can probably be dropped to 21. I think I picked 23 because that's when the fingerprint APIs were added and I figured there was no use for this view pre-23.

Your change shouldn't have any effect on the animation speed and I'm able to rapidly switch between states in the sample app without it getting stuck.

**Comment by MaxChinni** [comment]
Thank you for the answer.

Technically [Samsung Pass SDK](http://developer.samsung.com/galaxy#pass) requires devices with Android 4.2 Jelly Bean (API level 17) or above, but I get what you are saying.

**Comment by mattprecious** [comment]
I took at look at this yesterday. When I dropped the min SDK to 21 and used the existing code as-is, the icons looked absolutely terrible on API 21 and poor on 22. They were not crisp. I also saw the issue mentioned above where the animations just kind of stopped mid-way for no reason.

I pulled in the `support-vector-drawable` and `animated-vector-drawable` libraries and they look perfect, however, there are issues with the error animation. Thankfully, those are standalone libraries so they can be fixed! I've filed https://code.google.com/p/android/issues/detail?id=212734. If that gets fixed then I can drop the min SDK to 21.

**Comment by MaxChinni** [comment]
That makes sense.
Thanks again.

**Comment by jeffreyliu8** [comment]
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.mattprecious.swirl.SwirlView
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                                    at 
....................

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                                 Caused by: java.lang.AssertionError: API 23 required.

Better mention this api 23 thing in readme.

**Comment by mattprecious** [comment]
The min is now 21 on v1.1.0.
